INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "AerialSingleLumped"



  LUMP_DOMAINS: ["AID", "CLRS", "NWPU"]
  SOURCE_DOMAINS: ["AID"]
  TARGET_DOMAINS: ["REST"]

  SHARED_CLASSES: ["airport", "beach", "bridge", "forest", "industrial", "mountain", "parking", "port", "railway_station", "river", "stadium", "storage_tank"]

MODEL:
  BACKBONE:
    NAME: "resnet50"
